Docs: 각 db 모델에 updated_at 추가
CSchoice/iron_stone_instagram pull request #4
Opened 2024-04-16 08:42 UTC by CSchoice

Docs: 각 db 모델에 updated_at 추가

2024-04-16 13:22 UTC, BDlhj requested changes
1. 하나의 커밋으로 묶지 말고 수정사항 별로 더 세분화해서 커밋을 남기면 더 좋을 것 같아! 커밋 태그(Docs, Feat 등등)도 더 명확히 달아주면 더 좋고!
2. 이미 main으로 들어간 코드는 어쩔 수 없지만 앞으로는 PR 날릴 때 reviewer 지정해주면 가능한 빨리 확인해볼게~~!!
3. 우선 Request changes로 해둘테니까 수정하고 re-request 날려줘~~(아마 reviwer쪽 옆에 새로고침이랑 비슷한 버튼이 생겼던 것 같아)
4. LGTM👍🏻👍🏻👍🏻(Look Good To Me)

2024-04-16 13:22 UTC, BDlhj commented on contents/models.py
> +    updated_at = models.DateTimeField(auto_now_add=True)
파일의 맨 마지막에 new line을 추가해주면 저 빨간 표시가 안 나요~~

2024-04-16 13:22 UTC, BDlhj commented on docs/API_DOCS.md
DB 모델에 관한 문서이므로 Type도 프로젝트에서 사용하는 데이터베이스에 존재하는 자료형으로 작성해주면 더 좋을듯!

2024-04-17 15:21 UTC, CSchoice commented
62d43be 커밋 내용을 작성을 안 하고 날짜를 기입했네 ㅠㅠ

2024-04-18 14:40 UTC, BDlhj requested changes
굿굿 개발 속도가 아주 빠르구만👍🏻

2024-04-18 14:40 UTC, BDlhj commented on accounts/views.py
> +        return Response(serializer.data)
여기도 맨 마지막에 new line 만들어주기~!

2024-04-18 14:40 UTC, BDlhj commented on contents/models.py
> +
ditto(위와 같음)

2024-04-18 14:40 UTC, BDlhj commented on contents/models.py
> +    updated_at = models.DateTimeField(auto_now_add=True)
auto_now와 auto_now_add의 차이에 대해 다시 고민해보기

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +class Article_like_comment_Serializer(serializers.ModelSerializer):
python에서 class name은 camel case를 따릅니다~~
```suggestion
class ArticleLikeCommentSerializer(serializers.ModelSerializer):
```

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +#         return False
필요없는 코드는 지워주는 게 깔끔!

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +        return obj.like_user.count()
new line

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +    def get_liked_by_user(self, obj):
아마 한 줄 띄어주는 게 PEP8에 맞을 듯! 시간 되면 PEP8 찾아보는 것도 좋고!

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +    comments = serializers.SerializerMethodField()
nested serializer에 대해서 한번 찾아보면 좋을듯!

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +        if request and request.user.is_authenticated:
view에서 항상 request를 넘겨주니까 바로 authentication만 체크해도 될듯

2024-04-18 14:40 UTC, BDlhj commented on contents/serializers.py
> +class Article_like_comment_Serializer(serializers.ModelSerializer):
게시글 목록 조회용 serializer와 게시글 상세 조회용 serializer를 구분하면 더 좋아. 각각의 경우에 필요한 데이터가 다르니까!

2024-04-18 14:40 UTC, BDlhj commented on instagram/settings.py
> +CORS_ALLOW_ALL_ORIGINS = True
new line

2024-04-18 14:43 UTC, BDlhj commented
추가로, draft pr 날려달라고 한 건 처음에 API 명세 확인하려고 했던 거라서 이 pr은 닫고 다음부턴 그냥 pr 요청하면 될 거 같아
그래야 main으로 merge할듯!

2024-04-24 08:15 UTC, merged